; Inno Setup script for Virtual Gamepad Host.
#define MyAppName "Virtual Gamepad Host"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Atomprod"
#define MyAppURL "https://atomprod.in"
#define MyAppExeName "VirtualGamepadHost.exe"

[Setup]
AppId={{IN-ATOMPROD-VGAMEPAD-HOST-1A2B3C}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\VirtualGamepadHost
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma2
SolidCompression=yes
; FIX: Simplified output directory to build inside the current workspace
OutputDir=dist
OutputBaseFilename=VirtualGamepadHost-Setup
; FIX: Pointing directly to the publish folder generated by dotnet publish
SetupIconFile=publish\app_icon.ico
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: checkedonce

[Files]
; FIX: Removed "..\" so it looks inside the local "publish" folder
Source: "publish\VirtualGamepadHost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "publish\app_icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{userprograms}\Virtual Gamepad Host"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"
Name: "{userprograms}\Uninstall Virtual Gamepad Host"; Filename: "{uninstallexe}"
Name: "{userdesktop}\Virtual Gamepad Host"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\app_icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch Virtual Gamepad Host now"; Flags: nowait postinstall skipifsilent