name: virtual_gamepad
description: Turn your phone into a wireless Xbox-compatible gamepad for PC.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
